=== ponsger/TT2/xml/esquemaRespuestas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="respuestas" type="datos"/>
	<xs:complexType name="datos">
		<xs:sequence>
			<xs:element name="examenes" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="examen" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
					<xs:sequence>
						<xs:element name="ejercicio" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="numero" type="xs:integer"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="pregunta" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="numero" type="xs:integer"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="numero" type="xs:integer" use="required"/>
				</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ejercicios" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ejercicio" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="numero" type="xs:integer"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="preguntas" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="pregunta" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="numero" type="xs:integer"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== ponsger/TT2/ProjectFinalStruts/web/xml/respuestas.xml
<?xml version="1.0" encoding="UTF-8"?>
<respuestas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/gerpo/OneDrive/Escritorio/xml/esquemaRespuestas.xsd">
		<examenes>
		<examen numero="1">
			<ejercicio numero="1">2,4,3,1</ejercicio>
			<ejercicio numero="4">2,4,3,1</ejercicio>
			<pregunta numero="1">2,4,3,1</pregunta>
		</examen>
	</examenes>
    <ejercicios>
        <ejercicio numero="2">3,2,1,4</ejercicio>
        <ejercicio numero="2">3,2,1,4</ejercicio>
    </ejercicios>

    <preguntas>
        <pregunta numero="1">Aqui va la respuesta</pregunta>
    </preguntas>    
    
</respuestas>
