=== ponsger/TT2/xml/esquemaExamen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="examenes" type="datos"/>
	<xs:complexType name="datos">
		<xs:sequence>
			<xs:element name="examen" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ejercicio" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="numero" type="xs:integer"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="pregunta" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="numero" type="xs:integer"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="numero" type="xs:integer" use="required"/>
					<xs:attribute name="fecha" type="xs:string" use="required"/>
					<xs:attribute name="nombre" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== ponsger/TT2/ProjectFinalStruts/build/web/xml/examenes.xml
<?xml version="1.0" encoding="UTF-8"?>
<examenes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/gerpo/OneDrive/Escritorio/xml/esquemaExamen.xsd">
<examen fecha="2019-30-08" nombre="Primer parcial 2019" numero="1">
		<ejercicio numero="1"></ejercicio>
		<ejercicio numero="3"></ejercicio>
	</examen>
	<examen fecha="2019-15-10" nombre="Segundo parcial 2019" numero="2">
		<ejercicio numero="2"></ejercicio>
		<ejercicio numero="3"></ejercicio>
	</examen>
	<examen fecha="2019-08-11" nombre="Tercer parcial 2019" numero="3">
		<ejercicio numero="1"></ejercicio>
		<ejercicio numero="2"></ejercicio>
		<pregunta numero="3"></pregunta>
	</examen>
</examenes>
