=== ponsger/TT2/xml/esquemaEjercicio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ejercicios" type="datos"/>
	<xs:complexType name="datos">
		<xs:sequence>
			<xs:element name="ejercicio" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="indicaciones" type="xs:string"/>
						<xs:element name="opcion1" type="xs:string"/>
						<xs:element name="opcion2" type="xs:string"/>
						<xs:element name="opcion3" type="xs:string"/>
						<xs:element name="opcion4" type="xs:string"/>
						<xs:element name="resultado" type="xs:string"/>
					</xs:sequence>
					<xs:attribute name="numero" type="xs:integer" use="required"/>
					<xs:attribute name="tipo" type="xs:string" use="required"/>
					<xs:attribute name="nombre" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== ponsger/TT2/xml/ejercicios.xml
<?xml version="1.0" encoding="UTF-8"?>
<ejercicios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/gerpo/OneDrive/Escritorio/xml/esquemaEjercicio.xsd">
<ejercicio numero="1" tipo="Ordena" nombre="Ordena los números decimales">
    <indicaciones>Ordena los numeros de mayor a menor de arriba hacia abajo</indicaciones>
    <opcion1>0.69</opcion1>
    <opcion2>0.65</opcion2>
    <opcion3>0.32</opcion3>
    <opcion4>0.66</opcion4>
    <resultado>1,4,2,3</resultado>
  </ejercicio>
  
  <ejercicio numero="2" tipo="Ordena" nombre="Ordena números enteros con decimales">
    <indicaciones>Pinta de cualquier color el numero mas grande</indicaciones>
    <opcion1>2.54</opcion1>
    <opcion2>3.45</opcion2>
    <opcion3>5.32</opcion3>
    <opcion4>1.01</opcion4>
    <resultado>3,2,1,4</resultado>
  </ejercicio>
  
  <ejercicio numero="3" tipo="Ordena" nombre="Acomoda las fracciones de mayor a menor">
    <indicaciones>Acomoda de menor a mayor</indicaciones>
    <opcion1>1/100</opcion1>
    <opcion2>1/10</opcion2>
    <opcion3>1/50</opcion3>
    <opcion4>1/1</opcion4>
    <resultado>4,2,3,1</resultado>
  </ejercicio>
  </ejercicios>
